brew install --cask visual-studio-code
brew install --cask gitkraken
brew install --cask zoom
brew install --cask raycast
brew install --cask postman
brew install --cask mongodb-compass
brew install --cask docker
brew install --cask deepl
brew install --cask hyper
brew install --cask vlc
brew install --cask obsidian